author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /test-readux2
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://iiif.archivelab.org/iiif//01165245.4823.emory.edu$1/full/full/0/default.jpg
image_size:
  page:
    height: 1500
    width: 1950
permalink: pretty
publication_info:
  date: '2020'
  editors: []
  title: Lyrics of lowly life
show_annotation_author: true
source_info:
  title: Lyrics of lowly life
  via_readux: true
tagline: an annotated digital edition
title: Lyrics of lowly life
url: https://jayvarner.github.io
version: 0.7
